---

- name: install pkgs
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python3-yaml
      - python3-docker
      - dockerctl-{{ ansible_hostname }}






